server:
  port: 7002
  error:
    include-message: always

spring:
  mongodb:
    embedded:
      version: 3.4.0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---
spring:
  profiles: docker

  data:
    mongodb:
      host: mongodb

server.port: 8080