server:
  port: 7002
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation_db
  jpa:
    show-sql: true
    properties:
      format_sql: true

logging:
  level:
    root: INFO
    se.magnus: DEBUG